Repository Department-of-Administrative-Affairs/DM-CS-2-answers, pull requests merged in 2021-05, with the labels that each got.

#40 CS255 2020 paper answers
  CS255 Artificial Intelligence/2020/Question 1.md
  CS255 Artificial Intelligence/2020/Question 2.md
  CS255 Artificial Intelligence/2020/Question 2a i..jpg
  CS255 Artificial Intelligence/2020/Question 2a iii..jpg
  CS255 Artificial Intelligence/2020/Question 2a iv..jpg
  CS255 Artificial Intelligence/2020/Question 3.md
  CS255 Artificial Intelligence/2020/Question 4.md
  CS255 Artificial Intelligence/2020/Question 5.md
  CS255 Artificial Intelligence/2020/Question 5e i..jpg
  CS255 Artificial Intelligence/2020/Question 5e ii..jpg
  CS255 Artificial Intelligence/2020/Question 5e iii..jpg
  CS255 Artificial Intelligence/2020/Question 5e iv. (1).jpg
  CS255 Artificial Intelligence/2020/Question 5e iv. (2).jpg
Labels: enhancement

#42 Added answer 2bii to 2020 exam
  CS255 Artificial Intelligence/2020/Question 2.md
  CS255 Artificial Intelligence/2020/Question 3.md
  CS255 Artificial Intelligence/2020/Question 5.md
Labels: disputed, enhancement

#44 Updated 2020 Q2 a.iv
  CS255 Artificial Intelligence/2020/Question 2a iv..jpg
Labels: bug, duplicate

#45 Added answers for Part I in CS259 2020 paper
  CS259 Formal Languages/2020/Part I.md
  CS259 Formal Languages/2020/Part II Q1.md
  CS259 Formal Languages/2020/Part II Q2.md
  CS259 Formal Languages/2020/Question 1.md
  CS259 Formal Languages/2020/Question 2.md
  CS259 Formal Languages/2020/Question 3.md
Labels: enhancement

#46 Added answer for 2020 Q2a
  CS259 Formal Languages/2020/Part II Q2.md
Labels: enhancement

#47 Updated 2020 3c w/diagram
  CS255 Artificial Intelligence/2020/Question 3.md
Labels: enhancement

#48 Correct notation in 2020.1.2
  CS259 Formal Languages/2020/Part I.md
Labels: bug

#49 Fix incorrect name for probability law
  CS255 Artificial Intelligence/2020/Question 1.md
Labels: bug
