Repository Department-of-Administrative-Affairs/DM-CS-2-answers, pull requests merged in 2021-04, with the labels that each got.

#8 Question 1.md
  CS260 Algorithms/2020/Question 1.md
Labels: bug

#9 Changed colour of maths image to be visible in light and dark mode
  CS258 Databases/2020/Question 2.md
  README.md
Labels: enhancement

#11 Fixed error in Q3 a
  CS258 Databases/2020/Question 3.md
Labels: bug

#12 Update Question 4.md
  CS258 Databases/2020/Question 4.md
Labels: bug

#14 Fixed Part D
  CS258 Databases/2020/Question 1.md
Labels: bug

#17 Update Question4.md
  CS258 Databases/2018/Question 4.md
Labels: enhancement

#18 Update Question 5.md
  CS258 Databases/2018/Question 5.md
Labels: enhancement

#19 Update Question 5.md
  CS258 Databases/2018/Question 5.md
Labels: enhancement

#20 Quetion 1 2017 DB
  CS258 Databases/2017/Question 1.md
Labels: enhancement

#21 Small fix to explanation on question 1 c iii
  CS258 Databases/2017/Question 1.md
Labels: bug

#22 update 4.d.iii
  CS258 Databases/2018/Question 4.md
Labels: bug

#23 q5 answer
  CS258 Databases/2017/Question 5.md
Labels: enhancement

#24 Fix incorrect module name
  CS263 Cyber Security/2017/Question 1.md
  CS263 Cyber Security/2017/Question 2.md
  CS263 Cyber Security/2017/Question 3.md
  CS263 Cyber Security/2017/Question 4.md
  CS263 Cyber Security/2017/Question 5.md
  CS263 Cyber Security/2018/Question 1.md
  CS263 Cyber Security/2018/Question 2.md
  CS263 Cyber Security/2018/Question 3.md
  CS263 Cyber Security/2018/Question 4.md
  CS263 Cyber Security/2018/Question 5.md
  CS263 Cyber Security/2019/Question 1.md
  CS263 Cyber Security/2019/Question 2.md
  CS263 Cyber Security/2019/Question 3.md
  CS263 Cyber Security/2019/Question 4.md
  CS263 Cyber Security/2019/Question 5.md
  CS263 Cyber Security/2020/Question 1.md
  CS263 Cyber Security/2020/Question 2.md
  CS263 Cyber Security/2020/Question 3.md
  CS263 Cyber Security/2020/Question 4.md
  CS263 Cyber Security/2020/Question 5.md
  CS263 Cyber Security/practice/Question 1.md
  CS263 Cyber Security/practice/Question 2.md
  CS263 Cyber Security/practice/Question 3.md
  CS263 Cyber Security/practice/Question 4.md
  CS263 Cyber Security/practice/Question 5.md
Labels: enhancement

#25 Rest of the Questions plus Question 1 fix 2017 DB paper
  CS258 Databases/2017/Question 1.md
  CS258 Databases/2017/Question 2.md
  CS258 Databases/2017/Question 3.md
  CS258 Databases/2017/Question 4.md
  CS258 Databases/2017/Question 5.md
  CS258 Databases/2017/Question 6.md
Labels: enhancement

#27 Updated arrows and revised Question 3 d)
  CS258 Databases/2017/Question 3.md
  CS258 Databases/2017/Question 5.md
Labels: bug, enhancement

#28 Update Question 2.md
  CS258 Databases/2020/Question 2.md
Labels: bug

#26 CS263 Changes
  CS263 Cyber Security/2017/Question 1.md
  CS263 Cyber Security/2017/Question 2.md
  CS263 Cyber Security/2017/Question 3.md
  CS263 Cyber Security/2017/Question 4.md
  CS263 Cyber Security/2017/Question 5.md
  CS263 Cyber Security/README.md
Labels: bug, enhancement

#29 2018 Paper DB
  CS258 Databases/2018/Question 1.md
  CS258 Databases/2018/Question 2.md
  CS258 Databases/2018/Question 3.md
  CS258 Databases/2018/Question 4.md
  CS258 Databases/2018/Question 6.md
Labels: bug, enhancement

#30 DB 2019 Answers
  CS258 Databases/2019/Question 1.md
  CS258 Databases/2019/Question 2.md
  CS258 Databases/2019/Question 3.md
  CS258 Databases/2019/Question 4.md
  CS258 Databases/2019/Question 5.md
  CS258 Databases/2019/Question 6.md
Labels: enhancement

#31 Some fixes and alternative solutions to DB 2020 Paper
  CS258 Databases/2020/Question 1.md
  CS258 Databases/2020/Question 2.md
  CS258 Databases/2020/Question 3.md
Labels: bug, enhancement

#34 OS Questions for CS241 2020
  CS241 Operating Systems and Networks/2020/Question 1.md
  CS241 Operating Systems and Networks/2020/Question 2.md
  CS241 Operating Systems and Networks/2020/Question 3.md
Labels: enhancement

#36 Corrected Question 2 a ii 2020 CS260
  CS260 Algorithms/2020/Question 2.md
Labels: bug

#37 Fix to question 2 c ii after clarification
  CS241 Operating Systems and Networks/2020/Question 2.md
Labels: bug

#38 Fixed some silly maths mistakes in CS241 2020 Paper
  CS241 Operating Systems and Networks/2020/Question 3.md
  CS241 Operating Systems and Networks/2020/Question 4.md
Labels: bug
